# Root Sync
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: id-t1 # kpt-set: ${id}-t1
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME # kpt-set: ${repo-url}
    branch: main # kpt-set: ${repo-branch}
    dir: tier1/configcontroller/deploy/<env> # kpt-set: ${repo-dir}
    revision: HEAD # kpt-set: ${version}
    auth: token
    secretRef:
      name: git-creds
